service: digiwork
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment: ${file(./config/env.dev.json)}
package:
  individually: true
plugins:
  - serverless-functions-base-path
  - serverless-esbuild
  - serverless-offline
custom:
  functionsBasePath: ./lambdas
  esbuild:
    packager: yarn
    minify: false
    nativeZip: true
functions:
  - ${file(./modules/${opt:module,'auth'}-functions.json)}
  - ${file(./modules/${opt:module,'location'}-functions.json)}
  - ${file(./modules/${opt:module,'workstation'}-functions.json)}
  - ${file(./modules/${opt:module,'user'}-functions.json)}
  - ${file(./modules/${opt:module,'reservation'}-functions.json)}
  - ${file(./modules/${opt:module,'room'}-functions.json)}
